### PR TITLE
AngstyEnemy: Enemy that charges and knocks back the player

### PR DESCRIPTION
**Pull request by daniellimws**
AngstyEnemy provides an example on how we can move towards the player and rotate to face the player using the MoveToPlayer and RotateToPlayer methods exposed by the base Enemy class.

These functions are left to the children class to call themselves so that they have full control over their actions.

AngstyEnemy also provides an implementation for charging towards the player to attack it. When it hits the player, the player will be knocked back by a factor of the AngstyEnemy's velocity.

As the saying goes, united we stand. When all enemies charge towards the player, the player will fly backwards by a large amount.

The AngstyEnemy mesh is changed to a CSGBox so that the rotation can be seen.

Additionally, add gravity to player otherwise the player might fly out
of the game when hit.

Still doesn't have path finding towards the player, because the AStar class needs us to initialize it with some information about the room. So will do that after room gen is done.

Replace #111.

I did not create a base class for enemy attacks yet because this is the first enemy attack and I am not sure what function would be good to be made abstract yet. I think it would be more clear as we make the next attack. For example, at this point, I'm not sure what is common between ranged attacks and melee attacks.

### CODE REVIEW

**Review by owenl131 — COMMENTED** [review]
Seems alright to me

**Comment by jeffsieu** [comment]
Is it just me, or when the enemies are killed, there's some massive lag spike?

**Comment by daniellimws** [comment]
I think can say goodbye to this alr. Ok to close?

**Comment by jeffsieu** [comment]
I'm ok with closing

**Pull request closed without merging**
