### PR TITLE
Dotnet format

### PR DESCRIPTION
**Pull request by daniellimws**
Add dotnet format github actions

### CODE REVIEW

**Comment by daniellimws** [comment]
Nice la see `dotnet format` failed and there are comments under "file changes"

**Comment by jeffsieu** [comment]
Nice. So can fix back?

**Comment by daniellimws** [comment]
Can. After dinner.

**Comment by daniellimws** [comment]
Ok the sln file is by Godot too. But it's generated during build so I'm just gonna gitignore it.

**Pull request merged**
