### PR TITLE
Refactor Enemy HP to HealthEntity, add health bar

### LINKED ISSUE #103: Code clean up: Player health, general Entity class
Now only enemies have health. Should be more robust by having a general `Entity` class

- [x] Entity class with `Damage(float damage)` and die animation functions
- [x] Entities display health bar in some way
- [x] Player and Enemy subclass Entity

### PR DESCRIPTION
**Pull request by jeffsieu**
HealthEntity represents objects that have health and status effects. On death, it will call Die() which are implemented by subclasses to play death animations.

Player and Enemy now subclass HealthEntity.

Also, health bars have been added to HealthEntities.

image

There are these white bars that show how much damage the player has done.
image

Resolves #103

### CODE REVIEW

**Comment by starcasted** [comment]
How long does the white bar lasts and do they have the same depleting animation as the normal health bar?

**Comment by jeffsieu** [comment]
Wa harro. The white bar will take 1s to smoothly deplete. While the red part of the health depletes instantly

**Review by daniellimws — CHANGES_REQUESTED** [review]
image

Why are HeatLevelLeft and HeatLevelRight not under the same node?

Otherwise ok to merge

**Comment by jeffsieu** [comment]
lol cos needed to flip the left one by setting the scale to (-1,1), but the hbox keeps setting the scale back to (1,1). so it's like a hack

**Comment by daniellimws** [comment]
Ok hacker

**Pull request merged**
